server:
  port: 8082
spring:
  application:
    name: spring-cloud-order

eureka:
  client:
    service-url:
      defaultZone: http://qxj:123@localhost:8080/eureka/
  instance:
    prefer-ip-address: true

user:
  url: http://localhost:8081/user/

